In [4]:
#import sys
#sys.path.append('')
from nexsci import downloader as dl

FileNotFoundError: [Errno 2] No such file or directory: '/home/jp/.local/lib/python3.6/site-packages/nexsci-0.1.1-py3.6.egg'

In [2]:
keyword = 'all'

DF=dl.parse_data_columns(keyword)

In [3]:
DF.keys()

dict_keys(['default', 'planet', 'stellar', 'photometry', 'color'])

In [4]:
df=DF['default']
df.head()

,Database Column Name,Table Label,Description,Uncertainties Column (positive +) (negative -),Displayed String Name,Limit Column,Number of Measurements
0,pl_hostname,Host Star Name,Stellar name most commonly used in the literat...,NaN,NaN,NaN,NaN
1,pl_letter,Planet Letter,Letter assigned to the planetary component of ...,NaN,NaN,NaN,NaN
2,pl_discmethod,Discovery Method,Method by which the planet was first identified.,NaN,NaN,NaN,NaN
3,pl_pnum,Number of Planets in System,Number of planets in the planetary system.,NaN,NaN,NaN,NaN
4,pl_orbper,Orbital Period (days),Time the planet takes to make a complete orbit...,(+) pl_orbpererr1 (-) pl_orbpererr2,pl_orbperstr,pl_orbperlim,pl_orbpern

In [5]:
dl.get_param_names(DF,keyword)

'pl_bmassj,pl_facility,pl_st_nref,st_metfe,pl_pnum,pl_orbsmax,gaia_plx,pl_msinie,pl_status,st_ic,st_logg,pl_imppar,pl_ttvflag,pl_rads,pl_masse,st_nplc,st_radv,pl_kepflag,st_teff,st_metratio,pl_rade,pl_nnotes,pl_msinij,swasp_id,st_vj,st_rc,st_rah,st_naxa,st_irac3,st_actr,ra_str,pl_k2flag,st_nts,st_iras2,pl_orbper,st_nglc,st_irac4,st_jmh2,st_glon,pl_ratdor,pl_telescope,pl_tranmid,pl_trandep,gaia_pmdec,st_pm,pl_radj,pl_rvamp,gaia_pm,pl_occdep,hd_name,pl_orbtper,st_vjmrc,pl_letter,pl_def_refname,st_rad,pl_disc_refname,st_colorn,st_iras4,st_wise2,st_dist,pl_bmasse,st_bmvj,st_wise4,pl_tranflag,pl_dens,pl_insol,pl_orbincl,st_nimg,pl_discmethod,pl_astflag,st_plx,st_elat,pl_mnum,st_umbj,st_dens,st_lum,pl_name,st_bj,st_vsini,pl_edelink,st_h,gaia_pmra,st_age,pl_tsystemref,st_pmdec,pl_ratror,st_elon,st_spstr,pl_angsep,gaia_dist,st_vjmic,st_nspec,st_mass,st_iras1,pl_trandur,pl_bmassprov,st_irac2,pl_massj,st_photn,st_wise1,st_bmy,rowupdate,pl_omflag,st_mips1,pl_pelink,st_glat,pl_instrument,pl_rvflag,st_optband,pl_publ_date,st_j,st_pmra,st_optmag,ra,st_irac1,st_c1,st_actlx,dec_str,st_hmk2,pl_eqt,pl_disc,st_acts,st_uj,pl_cbflag,st_k,st_wise3,pl_hostname,st_iras3,dec,hip_name,pl_st_npar,pl_orbeccen,pl_orblper,st_m1,st_jmk2,gaia_gmag,pl_imgflag,st_mips2,pl_locale,st_mips3,st_nrvc'

In [6]:
download_url=dl.get_nexsci_download_url(keyword)
download_url[:100]

'http://exoplanetarchive.ipac.caltech.edu/cgi-bin/nstedAPI/nph-nstedAPI?table=exoplanets&select=pl_bm'

In [7]:
df=dl.fetch_csv(download_url)
df.head()

Downloading data from URL:
http://exoplanetarchive.ipac.caltech.edu/cgi-bin/nstedAPI/nph-nstedAPI?table=exoplanets

,pl_bmassj,pl_facility,pl_st_nref,st_metfe,pl_pnum,pl_orbsmax,gaia_plx,pl_msinie,pl_status,st_ic,...,pl_trandeperr2,pl_ratdorerr2,pl_tranmiderr2,pl_orbinclerr1,pl_rvamperr2,pl_massjerr2,pl_angseperr1,pl_bmassjerr1,pl_occdeperr1,st_metfeerr2
0,NaN,Kepler,9,-0.01,1,NaN,NaN,NaN,3,NaN,...,NaN,NaN,-0.00434,NaN,NaN,NaN,NaN,NaN,NaN,-0.167
1,NaN,Kepler,8,0.09,1,NaN,NaN,NaN,3,NaN,...,NaN,NaN,-0.00442,NaN,NaN,NaN,NaN,NaN,NaN,-0.150
2,NaN,Kepler,8,0.04,1,NaN,NaN,NaN,3,NaN,...,NaN,NaN,-0.00159,NaN,NaN,NaN,NaN,NaN,NaN,-0.163
3,NaN,Kepler,9,0.07,1,NaN,NaN,NaN,3,NaN,...,NaN,NaN,-0.00288,NaN,NaN,NaN,NaN,NaN,NaN,-0.139
4,NaN,Kepler,9,0.03,1,NaN,NaN,NaN,3,NaN,...,NaN,NaN,-0.00397,NaN,NaN,NaN,NaN,NaN,NaN,-0.159

## Shortcut

In [12]:
df=dl.download_nexsci(keyword,replace=True)

Downloading data from URL:
http://exoplanetarchive.ipac.caltech.edu/cgi-bin/nstedAPI/nph-nstedAPI?table=exoplanets

Saved: confirmed_planets.csv
in /home/jp/data/

In [13]:
hostname = 'WASP-33'

df=dl.query_nexsci(hostname,keyword='planet')
df.T.head()

                  2132
Unnamed: 0        2132
pl_bmassj          4.1
pl_facility  SuperWASP
pl_st_nref          16
st_metfe           NaN

In [1]:
import downloader as dl

df=dl.query_transit_params('HAT-P-44')
df

                 value      err1      err2
b         1.720000e-01  0.079000 -0.074000
ecc       4.400000e-02  0.052000 -0.052000
inc[deg]  8.910000e+01  0.400000 -0.400000
P[d]      4.301219e+00  0.000019 -0.000019
a[au]     5.070000e-02  0.000700 -0.000700
Rp[Rj]    1.242000e+00  0.106000 -0.051000
t0[d]     2.455697e+06  0.000240 -0.000240
Rs[Rsun]  9.500000e-01  0.080000 -0.040000
Rp/Rs     1.343487e-01  0.016108 -0.007901
a/Rs      1.147593e+01  0.979297 -0.508512